# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterStore.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QPushButton, QVBoxLayout, QFileDialog , QLabel, QTextEdit
from PyQt5.QtGui import QPixmap

class RegisterStoreView(object):
    def __init__(self, MainWindow, user, shop, schedule):
        self.name = ""
        self.address = ""
        self.number = ""
        self.type = ""
        self.description = ""
        self.streetname = ""
        self.streetnumber = ""
        self.schedule = []
        shop.photos = ["../view/image.png","../view/image.png","../view/image.png","../view/image.png","../view/image.png"]
        self.flagPhoto = False
        self.flagType = False
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Inicio/mapa.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame.setStyleSheet("background-color: rgb(3, 48, 118,180);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Name_app_3 = QtWidgets.QLabel(self.frame)
        self.Name_app_3.setGeometry(QtCore.QRect(170, 27, 521, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Name_app_3.setFont(font)
        self.Name_app_3.setStyleSheet("font: 70px \"Segoe Print\";\n"
"color: rgb(230, 230, 230);\n"
"background: transparent;")
        self.Name_app_3.setObjectName("Name_app_3")
        self.Name_app_4 = QtWidgets.QLabel(self.frame)
        self.Name_app_4.setGeometry(QtCore.QRect(170, 30, 511, 101))
        self.Name_app_4.setStyleSheet("font: 70px \"Segoe Print\";\n"
"color: rgb(83, 83, 83);\n"
"background: transparent;")
        self.Name_app_4.setObjectName("Name_app_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 170, 241, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(254, 252, 224,60);\n"
"border:1px solid black;\n"
"border-radius: 6px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 170, 241, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(254, 252, 224,60);\n"
"border:1px solid black;\n"
"border-radius: 6px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(630, 170, 91, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(254, 252, 224,60);\n"
"border:1px solid black;\n"
"border-radius: 6px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(380, 210, 121, 31))
        self.label_2.setStyleSheet("background: transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(225,225,225);")
        self.label_2.setObjectName("label_2")
        self.toolBox = QtWidgets.QToolBox(self.frame)
        self.toolBox.setEnabled(True)
        self.toolBox.setGeometry(QtCore.QRect(80, 240, 251, 321))
        self.toolBox.setStyleSheet("background-color:rgb(188, 188, 188,60);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.Monday = QtWidgets.QWidget()
        self.Monday.setEnabled(True)
        self.Monday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Monday.setMouseTracking(False)
        self.Monday.setTabletTracking(False)
        self.Monday.setAcceptDrops(False)
        self.Monday.setObjectName("Monday")
        self.timeEdit_Open_Monday1 = QtWidgets.QTimeEdit(self.Monday)
        self.timeEdit_Open_Monday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Monday1.setStyleSheet("color: black")
        self.timeEdit_Open_Monday1.setObjectName("timeEdit_Open_Monday1")
        self.label_3 = QtWidgets.QLabel(self.Monday)
        self.label_3.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_3.setObjectName("label_3")
        self.timeEdit_Close_Monday1 = QtWidgets.QTimeEdit(self.Monday)
        self.timeEdit_Close_Monday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Monday1.setStyleSheet("color: black")
        self.timeEdit_Close_Monday1.setObjectName("timeEdit_Close_Monday1")
        self.label_4 = QtWidgets.QLabel(self.Monday)
        self.label_4.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_4.setObjectName("label_4")
        self.timeEdit_Open_Monday2 = QtWidgets.QTimeEdit(self.Monday)
        self.timeEdit_Open_Monday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Monday2.setStyleSheet("color: black")
        self.timeEdit_Open_Monday2.setObjectName("timeEdit_Open_Monday2")
        self.label_5 = QtWidgets.QLabel(self.Monday)
        self.label_5.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_5.setObjectName("label_5")
        self.timeEdit_Close_Monday2 = QtWidgets.QTimeEdit(self.Monday)
        self.timeEdit_Close_Monday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Monday2.setStatusTip("")
        self.timeEdit_Close_Monday2.setStyleSheet("color: black")
        self.timeEdit_Close_Monday2.setKeyboardTracking(False)
        self.timeEdit_Close_Monday2.setObjectName("timeEdit_Close_Monday2")
        self.label_6 = QtWidgets.QLabel(self.Monday)
        self.label_6.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_6.setObjectName("label_6")
        self.checkBox_Monday = QtWidgets.QCheckBox(self.Monday)
        self.checkBox_Monday.setEnabled(True)
        self.checkBox_Monday.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday.setText("")
        self.checkBox_Monday.setChecked(True)
        self.checkBox_Monday.setObjectName("checkBox_Monday")
        self.toolBox.addItem(self.Monday, "")
        self.Tuesday = QtWidgets.QWidget()
        self.Tuesday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Tuesday.setObjectName("Tuesday")
        self.timeEdit_Open_Tuesday1 = QtWidgets.QTimeEdit(self.Tuesday)
        self.timeEdit_Open_Tuesday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Tuesday1.setStyleSheet("color: black")
        self.timeEdit_Open_Tuesday1.setObjectName("timeEdit_Open_Tuesday1")
        self.label_7 = QtWidgets.QLabel(self.Tuesday)
        self.label_7.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Tuesday)
        self.label_8.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_8.setObjectName("label_8")
        self.timeEdit_Close_Tuesday2 = QtWidgets.QTimeEdit(self.Tuesday)
        self.timeEdit_Close_Tuesday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Tuesday2.setStyleSheet("color: black")
        self.timeEdit_Close_Tuesday2.setObjectName("timeEdit_Close_Tuesday2")
        self.label_9 = QtWidgets.QLabel(self.Tuesday)
        self.label_9.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_9.setObjectName("label_9")
        self.timeEdit_Close_Tuesday1 = QtWidgets.QTimeEdit(self.Tuesday)
        self.timeEdit_Close_Tuesday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Tuesday1.setStyleSheet("color: black")
        self.timeEdit_Close_Tuesday1.setObjectName("timeEdit_Close_Tuesday1")
        self.label_10 = QtWidgets.QLabel(self.Tuesday)
        self.label_10.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_10.setObjectName("label_10")
        self.timeEdit_Open_Tuesday2 = QtWidgets.QTimeEdit(self.Tuesday)
        self.timeEdit_Open_Tuesday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Tuesday2.setStyleSheet("color: black")
        self.timeEdit_Open_Tuesday2.setObjectName("timeEdit_Open_Tuesday2")
        self.checkBox_Monday_2 = QtWidgets.QCheckBox(self.Tuesday)
        self.checkBox_Monday_2.setEnabled(True)
        self.checkBox_Monday_2.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday_2.setText("")
        self.checkBox_Monday_2.setChecked(True)
        self.checkBox_Monday_2.setObjectName("checkBox_Monday_2")
        self.toolBox.addItem(self.Tuesday, "")
        self.Wednesday = QtWidgets.QWidget()
        self.Wednesday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Wednesday.setObjectName("Wednesday")
        self.timeEdit_Open_Wednesday1 = QtWidgets.QTimeEdit(self.Wednesday)
        self.timeEdit_Open_Wednesday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Wednesday1.setStyleSheet("color: black")
        self.timeEdit_Open_Wednesday1.setObjectName("timeEdit_Open_Wednesday1")
        self.label_11 = QtWidgets.QLabel(self.Wednesday)
        self.label_11.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Wednesday)
        self.label_12.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_12.setObjectName("label_12")
        self.timeEdit_Close_Wednesday2 = QtWidgets.QTimeEdit(self.Wednesday)
        self.timeEdit_Close_Wednesday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Wednesday2.setStyleSheet("color: black")
        self.timeEdit_Close_Wednesday2.setObjectName("timeEdit_Close_Wednesday2")
        self.label_13 = QtWidgets.QLabel(self.Wednesday)
        self.label_13.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_13.setObjectName("label_13")
        self.timeEdit_Close_Wednesday1 = QtWidgets.QTimeEdit(self.Wednesday)
        self.timeEdit_Close_Wednesday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Wednesday1.setStyleSheet("color: black")
        self.timeEdit_Close_Wednesday1.setObjectName("timeEdit_Close_Wednesday1")
        self.label_14 = QtWidgets.QLabel(self.Wednesday)
        self.label_14.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_14.setObjectName("label_14")
        self.timeEdit_Open_Wednesday2 = QtWidgets.QTimeEdit(self.Wednesday)
        self.timeEdit_Open_Wednesday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Wednesday2.setStyleSheet("color: black")
        self.timeEdit_Open_Wednesday2.setObjectName("timeEdit_Open_Wednesday2")
        self.checkBox_Monday_3 = QtWidgets.QCheckBox(self.Wednesday)
        self.checkBox_Monday_3.setEnabled(True)
        self.checkBox_Monday_3.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday_3.setText("")
        self.checkBox_Monday_3.setChecked(True)
        self.checkBox_Monday_3.setObjectName("checkBox_Monday_3")
        self.toolBox.addItem(self.Wednesday, "")
        self.Thursday = QtWidgets.QWidget()
        self.Thursday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Thursday.setObjectName("Thursday")
        self.timeEdit_Open_Thursday1 = QtWidgets.QTimeEdit(self.Thursday)
        self.timeEdit_Open_Thursday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Thursday1.setStyleSheet("color: black")
        self.timeEdit_Open_Thursday1.setObjectName("timeEdit_Open_Thursday1")
        self.label_15 = QtWidgets.QLabel(self.Thursday)
        self.label_15.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Thursday)
        self.label_16.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_16.setObjectName("label_16")
        self.timeEdit_Close_Thursday2 = QtWidgets.QTimeEdit(self.Thursday)
        self.timeEdit_Close_Thursday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Thursday2.setStyleSheet("color: black")
        self.timeEdit_Close_Thursday2.setObjectName("timeEdit_Close_Thursday2")
        self.label_17 = QtWidgets.QLabel(self.Thursday)
        self.label_17.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_17.setObjectName("label_17")
        self.timeEdit_Close_Thursday1 = QtWidgets.QTimeEdit(self.Thursday)
        self.timeEdit_Close_Thursday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Thursday1.setStyleSheet("color: black")
        self.timeEdit_Close_Thursday1.setObjectName("timeEdit_Close_Thursday1")
        self.label_18 = QtWidgets.QLabel(self.Thursday)
        self.label_18.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_18.setObjectName("label_18")
        self.timeEdit_Open_Thursday2 = QtWidgets.QTimeEdit(self.Thursday)
        self.timeEdit_Open_Thursday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Thursday2.setStyleSheet("color: black")
        self.timeEdit_Open_Thursday2.setObjectName("timeEdit_Open_Thursday2")
        self.checkBox_Monday_4 = QtWidgets.QCheckBox(self.Thursday)
        self.checkBox_Monday_4.setEnabled(True)
        self.checkBox_Monday_4.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday_4.setText("")
        self.checkBox_Monday_4.setChecked(True)
        self.checkBox_Monday_4.setObjectName("checkBox_Monday_4")
        self.toolBox.addItem(self.Thursday, "")
        self.Friday = QtWidgets.QWidget()
        self.Friday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Friday.setObjectName("Friday")
        self.timeEdit_Open_Frisday1 = QtWidgets.QTimeEdit(self.Friday)
        self.timeEdit_Open_Frisday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Frisday1.setStyleSheet("color: black")
        self.timeEdit_Open_Frisday1.setObjectName("timeEdit_Open_Frisday1")
        self.label_19 = QtWidgets.QLabel(self.Friday)
        self.label_19.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Friday)
        self.label_20.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_20.setObjectName("label_20")
        self.timeEdit_Close_Frisday2 = QtWidgets.QTimeEdit(self.Friday)
        self.timeEdit_Close_Frisday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Frisday2.setStyleSheet("color: black")
        self.timeEdit_Close_Frisday2.setObjectName("timeEdit_Close_Frisday2")
        self.label_21 = QtWidgets.QLabel(self.Friday)
        self.label_21.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_21.setObjectName("label_21")
        self.timeEdit_Close_Frisday1 = QtWidgets.QTimeEdit(self.Friday)
        self.timeEdit_Close_Frisday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Frisday1.setStyleSheet("color: black")
        self.timeEdit_Close_Frisday1.setObjectName("timeEdit_Close_Frisday1")
        self.label_22 = QtWidgets.QLabel(self.Friday)
        self.label_22.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_22.setObjectName("label_22")
        self.timeEdit_Open_Frisday2 = QtWidgets.QTimeEdit(self.Friday)
        self.timeEdit_Open_Frisday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Frisday2.setStyleSheet("color: black")
        self.timeEdit_Open_Frisday2.setObjectName("timeEdit_Open_Frisday2")
        self.checkBox_Monday_5 = QtWidgets.QCheckBox(self.Friday)
        self.checkBox_Monday_5.setEnabled(True)
        self.checkBox_Monday_5.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday_5.setText("")
        self.checkBox_Monday_5.setChecked(True)
        self.checkBox_Monday_5.setObjectName("checkBox_Monday_5")
        self.toolBox.addItem(self.Friday, "")
        self.Saturday = QtWidgets.QWidget()
        self.Saturday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Saturday.setObjectName("Saturday")
        self.timeEdit_Open_Saturday1 = QtWidgets.QTimeEdit(self.Saturday)
        self.timeEdit_Open_Saturday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Saturday1.setStyleSheet("color: black")
        self.timeEdit_Open_Saturday1.setObjectName("timeEdit_Open_Saturday1")
        self.label_23 = QtWidgets.QLabel(self.Saturday)
        self.label_23.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Saturday)
        self.label_24.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_24.setObjectName("label_24")
        self.timeEdit_Close_Saturday2 = QtWidgets.QTimeEdit(self.Saturday)
        self.timeEdit_Close_Saturday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Saturday2.setStyleSheet("color: black")
        self.timeEdit_Close_Saturday2.setObjectName("timeEdit_Close_Saturday2")
        self.label_25 = QtWidgets.QLabel(self.Saturday)
        self.label_25.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_25.setObjectName("label_25")
        self.timeEdit_Close_Saturday1 = QtWidgets.QTimeEdit(self.Saturday)
        self.timeEdit_Close_Saturday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Saturday1.setStyleSheet("color: black")
        self.timeEdit_Close_Saturday1.setObjectName("timeEdit_Close_Saturday1")
        self.label_26 = QtWidgets.QLabel(self.Saturday)
        self.label_26.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_26.setObjectName("label_26")
        self.timeEdit_Open_Saturday1Open_Saturday2 = QtWidgets.QTimeEdit(self.Saturday)
        self.timeEdit_Open_Saturday1Open_Saturday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Saturday1Open_Saturday2.setStyleSheet("color: black")
        self.timeEdit_Open_Saturday1Open_Saturday2.setObjectName("timeEdit_Open_Saturday1Open_Saturday2")
        self.checkBox_Monday_6 = QtWidgets.QCheckBox(self.Saturday)
        self.checkBox_Monday_6.setEnabled(True)
        self.checkBox_Monday_6.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday_6.setText("")
        self.checkBox_Monday_6.setChecked(True)
        self.checkBox_Monday_6.setObjectName("checkBox_Monday_6")
        self.toolBox.addItem(self.Saturday, "")
        self.Sunday = QtWidgets.QWidget()
        self.Sunday.setGeometry(QtCore.QRect(0, 0, 251, 97))
        self.Sunday.setObjectName("Sunday")
        self.timeEdit_Open_Sunday1 = QtWidgets.QTimeEdit(self.Sunday)
        self.timeEdit_Open_Sunday1.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.timeEdit_Open_Sunday1.setStyleSheet("color: black")
        self.timeEdit_Open_Sunday1.setObjectName("timeEdit_Open_Sunday1")
        self.label_27 = QtWidgets.QLabel(self.Sunday)
        self.label_27.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.Sunday)
        self.label_28.setGeometry(QtCore.QRect(50, 50, 51, 16))
        self.label_28.setObjectName("label_28")
        self.timeEdit_Close_Sunday2 = QtWidgets.QTimeEdit(self.Sunday)
        self.timeEdit_Close_Sunday2.setGeometry(QtCore.QRect(150, 70, 81, 22))
        self.timeEdit_Close_Sunday2.setStyleSheet("color: black")
        self.timeEdit_Close_Sunday2.setObjectName("timeEdit_Close_Sunday2")
        self.label_29 = QtWidgets.QLabel(self.Sunday)
        self.label_29.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_29.setObjectName("label_29")
        self.timeEdit_Close_Sunday1 = QtWidgets.QTimeEdit(self.Sunday)
        self.timeEdit_Close_Sunday1.setGeometry(QtCore.QRect(150, 20, 81, 22))
        self.timeEdit_Close_Sunday1.setStyleSheet("color: black")
        self.timeEdit_Close_Sunday1.setObjectName("timeEdit_Close_Sunday1")
        self.label_30 = QtWidgets.QLabel(self.Sunday)
        self.label_30.setGeometry(QtCore.QRect(160, 0, 51, 16))
        self.label_30.setObjectName("label_30")
        self.timeEdit_Open_Sunday2 = QtWidgets.QTimeEdit(self.Sunday)
        self.timeEdit_Open_Sunday2.setGeometry(QtCore.QRect(40, 70, 81, 22))
        self.timeEdit_Open_Sunday2.setStyleSheet("color: black")
        self.timeEdit_Open_Sunday2.setObjectName("timeEdit_Open_Sunday2")
        self.checkBox_Monday_7 = QtWidgets.QCheckBox(self.Sunday)
        self.checkBox_Monday_7.setEnabled(True)
        self.checkBox_Monday_7.setGeometry(QtCore.QRect(10, 10, 20, 17))
        self.checkBox_Monday_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.checkBox_Monday_7.setText("")
        self.checkBox_Monday_7.setChecked(True)
        self.checkBox_Monday_7.setObjectName("checkBox_Monday_7")
        self.toolBox.addItem(self.Sunday, "")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(80, 210, 141, 31))
        self.label_31.setStyleSheet("background: transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(225,225,225);")
        self.label_31.setObjectName("label_31")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(380, 240, 341, 111))
        self.textEdit.setStyleSheet("background-color:rgb(188, 188, 188,60);\n"
"border: transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_Create_Store = QtWidgets.QPushButton(self.frame)
        self.pushButton_Create_Store.setGeometry(QtCore.QRect(390, 530, 151, 51))
        self.pushButton_Create_Store.setStyleSheet("background-color: rgb(20, 100, 246);\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-radius: 6px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.pushButton_Create_Store.setObjectName("pushButton_Create_Store")
        self.pushButton_Cancel = QtWidgets.QPushButton(self.frame)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(560, 530, 151, 51))
        self.pushButton_Cancel.setStyleSheet("background-color: rgb(20, 100, 246);\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-radius: 6px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(380, 140, 121, 31))
        self.label_32.setStyleSheet("background: transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(225,225,225);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(630, 140, 31, 31))
        self.label_33.setStyleSheet("background: transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(225,225,225);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(80, 140, 121, 31))
        self.label_34.setStyleSheet("background: transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(225,225,225);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(380, 370, 61, 51))
        self.label_35.setStyleSheet("background-color: transparent;")
        self.label_35.setText("")
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_35.setPixmap(QtGui.QPixmap(shop.photos[0])) #LA IMAGEN NO SE PUEDE ACHICAR TANTO
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(450, 370, 61, 51))
        self.label_36.setStyleSheet("background-color: transparent;")
        self.label_36.setText("")
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_36.setPixmap(QtGui.QPixmap(shop.photos[1]))
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(520, 370, 61, 51))
        self.label_37.setStyleSheet("background-color: transparent;")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_37.setScaledContents(True)
        self.label_37.setPixmap(QtGui.QPixmap(shop.photos[2]))
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setGeometry(QtCore.QRect(590, 370, 61, 51))
        self.label_38.setStyleSheet("background-color: transparent;")
        self.label_38.setScaledContents(True)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_38.setPixmap(QtGui.QPixmap(shop.photos[3]))
        self.label_39 = QtWidgets.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(660, 370, 61, 51))
        self.label_39.setStyleSheet("background-color: transparent;")
        self.label_39.setText("")
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_39.setPixmap(QtGui.QPixmap(shop.photos[4]))
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(380, 430, 61, 21))
        self.pushButton.setStyleSheet("background-color:rgb(179, 179, 179);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 430, 61, 21))
        self.pushButton_2.setStyleSheet("background-color:rgb(179, 179, 179);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 430, 61, 21))
        self.pushButton_3.setStyleSheet("background-color:rgb(179, 179, 179);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 430, 61, 21))
        self.pushButton_4.setStyleSheet("background-color:rgb(179, 179, 179);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 430, 61, 21))
        self.pushButton_5.setStyleSheet("background-color:rgb(179, 179, 179);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.Name_app_4.raise_()
        self.Name_app_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_2.raise_()
        self.toolBox.raise_()
        self.label_31.raise_()
        self.textEdit.raise_()
        self.pushButton_Create_Store.raise_()
        self.pushButton_Cancel.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()

        self.radioButton_restaurant = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_restaurant.setGeometry(QtCore.QRect(470, 470, 82, 17))
        self.radioButton_restaurant.setObjectName("radioButton_restaurant")
        self.radioButton_restaurant.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_kitchen = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_kitchen.setGeometry(QtCore.QRect(560, 470, 82, 17))
        self.radioButton_kitchen.setObjectName("radioButton_kitchen")
        self.radioButton_kitchen.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_gardening = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_gardening.setGeometry(QtCore.QRect(650, 470, 82, 17))
        self.radioButton_gardening.setObjectName("radioButton_gardening")
        self.radioButton_gardening.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_bookstore = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_bookstore.setGeometry(QtCore.QRect(380, 490, 82, 17))
        self.radioButton_bookstore.setObjectName("radioButton_bookstore")
        self.radioButton_bookstore.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_toystore = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_toystore.setGeometry(QtCore.QRect(470, 490, 82, 17))
        self.radioButton_toystore.setObjectName("radioButton_toystore")
        self.radioButton_toystore.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_tools = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_tools.setGeometry(QtCore.QRect(560, 490, 82, 17))
        self.radioButton_tools.setObjectName("radioButton_tools")
        self.radioButton_tools.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_other = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_other.setGeometry(QtCore.QRect(650, 490, 82, 17))
        self.radioButton_other.setObjectName("radioButton_other")
        self.radioButton_other.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_sports = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_sports.setGeometry(QtCore.QRect(380, 470, 82, 17))
        self.radioButton_sports.setObjectName("radioButton_sports")
        self.radioButton_sports.setStyleSheet("color: rgb(255, 255, 255);")

        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(lambda: self.openFileNameDialog(MainWindow, shop, 1))
        self.pushButton_2.clicked.connect(lambda: self.openFileNameDialog(MainWindow, shop, 2))
        self.pushButton_3.clicked.connect(lambda: self.openFileNameDialog(MainWindow, shop, 3))
        self.pushButton_4.clicked.connect(lambda: self.openFileNameDialog(MainWindow, shop, 4))
        self.pushButton_5.clicked.connect(lambda: self.openFileNameDialog(MainWindow, shop, 5))
        self.pushButton_Create_Store.clicked.connect(lambda: self.actualizar(shop))

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def openFileNameDialog(self, MainWindow, shop, i):
        self.fileName, _ = QFileDialog.getOpenFileName(MainWindow,"QFileDialog.getOpenFileName()", "","All Files (*);;Python Files (*.py)")
        print(self.fileName)
        if self.fileName:
            self.flagPhoto = True
            if i == 1:
                shop.photos[0] = self.fileName
                self.label_35.setPixmap(QtGui.QPixmap(shop.photos[0]))
            if i == 2:
                shop.photos[1] = self.fileName
                self.label_36.setPixmap(QtGui.QPixmap(shop.photos[1]))
            if i == 3:
                shop.photos[2] = self.fileName
                self.label_37.setPixmap(QtGui.QPixmap(shop.photos[2]))
            if i == 4:
                shop.photos[3] = self.fileName
                self.label_38.setPixmap(QtGui.QPixmap(shop.photos[3]))
            if i == 5:
                shop.photos[4] = self.fileName
                self.label_39.setPixmap(QtGui.QPixmap(shop.photos[4]))
        '''else:
            if i == 1:
                shop.photos[0] = "../view/image.png"
                self.label_35.setPixmap(QtGui.QPixmap(shop.photos[0]))
            if i == 2:
                shop.photos[1] = "../view/image.png"
                self.label_36.setPixmap(QtGui.QPixmap(shop.photos[1]))
            if i == 3:
                shop.photos[2] = "../view/image.png"
                self.label_37.setPixmap(QtGui.QPixmap(shop.photos[2]))
            if i == 4:
                shop.photos[3] = "../view/image.png"
                self.label_38.setPixmap(QtGui.QPixmap(shop.photos[3]))
            if i == 5:
                shop.photos[4] = "../view/image.png"
                self.label_39.setPixmap(QtGui.QPixmap(shop.photos[4]))
'''
    def actualizar(self, shop):
        shop.name = self.lineEdit.text()
        shop.address = self.lineEdit_2.text()
        shop.number = self.lineEdit_3.text()
        shop.description = self.textEdit.toPlainText()
        if self.checkBox_Monday.isChecked():
            self.schedule.append(["Monday","Morning",str(self.timeEdit_Open_Monday1.time().hour()) + ":" + str(self.timeEdit_Open_Monday1.time().minute()),str(self.timeEdit_Close_Monday1.time().hour()) + ":" + str(self.timeEdit_Close_Monday1.time().minute())])
            self.schedule.append(["Monday","Afternoon",str(self.timeEdit_Open_Monday2.time().hour()) + ":" + str(self.timeEdit_Open_Monday2.time().minute()),str(self.timeEdit_Close_Monday2.time().hour()) + ":" + str(self.timeEdit_Close_Monday2.time().minute())])
        if self.checkBox_Monday_2.isChecked():
            self.schedule.append(["Tuesday","Morning",str(self.timeEdit_Open_Tuesday1.time().hour()) + ":" + str(self.timeEdit_Open_Tuesday1.time().minute()),str(self.timeEdit_Close_Tuesday1.time().hour()) + ":" + str(self.timeEdit_Close_Tuesday1.time().minute())])
            self.schedule.append(["Tuesday","Afternoon",str(self.timeEdit_Open_Tuesday2.time().hour()) + ":" + str(self.timeEdit_Open_Tuesday2.time().minute()),str(self.timeEdit_Close_Tuesday2.time().hour()) + ":" + str(self.timeEdit_Close_Tuesday2.time().minute())])
        if self.checkBox_Monday_3.isChecked():
            self.schedule.append(["Wednesday","Morning",str(self.timeEdit_Open_Wednesday1.time().hour()) + ":" + str(self.timeEdit_Open_Wednesday1.time().minute()),str(self.timeEdit_Close_Wednesday1.time().hour()) + ":" + str(self.timeEdit_Close_Wednesday1.time().minute())])
            self.schedule.append(["Wednesday","Afternoon",str(self.timeEdit_Open_Wednesday2.time().hour()) + ":" + str(self.timeEdit_Open_Wednesday2.time().minute()),str(self.timeEdit_Close_Wednesday2.time().hour()) + ":" + str(self.timeEdit_Close_Wednesday2.time().minute())])
        if self.checkBox_Monday_4.isChecked():
            self.schedule.append(["Thursday","Morning",str(self.timeEdit_Open_Thursday1.time().hour()) + ":" + str(self.timeEdit_Open_Thursday1.time().minute()),str(self.timeEdit_Close_Thursday1.time().hour()) + ":" + str(self.timeEdit_Close_Thursday1.time().minute())])
            self.schedule.append(["Thursday","Afternoon",str(self.timeEdit_Open_Thursday2.time().hour()) + ":" + str(self.timeEdit_Open_Thursday2.time().minute()),str(self.timeEdit_Close_Thursday2.time().hour()) + ":" + str(self.timeEdit_Close_Thursday2.time().minute())])
        if self.checkBox_Monday_5.isChecked():
            self.schedule.append(["Friday","Morning",str(self.timeEdit_Open_Frisday1.time().hour()) + ":" + str( self.timeEdit_Open_Frisday1.time().minute()),str(self.timeEdit_Close_Frisday1.time().hour()) + ":" + str(self.timeEdit_Close_Frisday1.time().minute())])
            self.schedule.append(["Friday","Afternoon",str(self.timeEdit_Open_Frisday2.time().hour()) + ":" + str( self.timeEdit_Open_Frisday2.time().minute()),str(self.timeEdit_Close_Frisday1.time().hour()) + ":" + str(self.timeEdit_Close_Frisday1.time().minute())])
        if self.checkBox_Monday_6.isChecked():
            self.schedule.append(["Saturday","Morning",str(self.timeEdit_Open_Saturday1.time().hour()) + ":" + str(self.timeEdit_Open_Saturday1.time().minute()),str(self.timeEdit_Close_Saturday1.time().hour()) + ":" + str(self.timeEdit_Close_Saturday1.time().minute())])
            self.schedule.append(["Saturday","Afternoon",str(self.timeEdit_Open_Saturday1Open_Saturday2.time().hour()) + ":" + str(self.timeEdit_Open_Saturday1Open_Saturday2.time().minute()),str(self.timeEdit_Close_Saturday2.time().hour()) + ":" + str(self.timeEdit_Close_Saturday2.time().minute())])
        if self.checkBox_Monday_7.isChecked():
            self.schedule.append(["Sunday","Morning",str(self.timeEdit_Open_Sunday1.time().hour()) + ":" + str(self.timeEdit_Open_Sunday1.time().minute()),str(self.timeEdit_Close_Sunday1.time().hour()) + ":" + str(self.timeEdit_Close_Sunday1.time().minute())])
            self.schedule.append(["Sunday","Afternoon",str(self.timeEdit_Open_Sunday2.time().hour()) + ":" + str(self.timeEdit_Open_Sunday2.time().minute()),str(self.timeEdit_Close_Sunday2.time().hour()) + ":" + str(self.timeEdit_Close_Sunday2.time().minute())])
        
        if self.radioButton_sports.isChecked() or self.radioButton_restaurant.isChecked() or self.radioButton_kitchen.isChecked() or self.radioButton_gardening.isChecked() or self.radioButton_bookstore.isChecked() or self.radioButton_toystore.isChecked() or self.radioButton_tools.isChecked() or self.radioButton_other.isChecked():
            self.flagType = True
            if self.radioButton_sports.isChecked():
                shop.type = "Sports"
            if self.radioButton_restaurant.isChecked():
                shop.type = "Restaurant"
            if self.radioButton_kitchen.isChecked():
                shop.type = "Kitchen"
            if self.radioButton_gardening.isChecked():
                shop.type = "Gardening"
            if self.radioButton_bookstore.isChecked():
                shop.type = "Bookstore"
            if self.radioButton_toystore.isChecked():
                shop.type = "Toy Store"
            if self.radioButton_tools.isChecked():
                shop.type = "Tools"
            if self.radioButton_other.isChecked():
                shop.type = "Other"
        print("tipo: ",self.type)
        print("bandera tipo: ",self.flagType)
        print("Schedule:", self.schedule)
        print(shop.name," ",shop.address," ",shop.number," ",shop.description)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name_app_3.setText(_translate("MainWindow", "Register Store"))
        self.Name_app_4.setText(_translate("MainWindow", "Register Store"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Name Store"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Address"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "N°"))
        self.label_2.setText(_translate("MainWindow", "Description:"))
        self.label_3.setText(_translate("MainWindow", "Open"))
        self.label_4.setText(_translate("MainWindow", "Close"))
        self.label_5.setText(_translate("MainWindow", "Open"))
        self.label_6.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Monday), _translate("MainWindow", "Monday"))
        self.label_7.setText(_translate("MainWindow", "Open"))
        self.label_8.setText(_translate("MainWindow", "Open"))
        self.label_9.setText(_translate("MainWindow", "Close"))
        self.label_10.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Tuesday), _translate("MainWindow", "Tuesday"))
        self.label_11.setText(_translate("MainWindow", "Open"))
        self.label_12.setText(_translate("MainWindow", "Open"))
        self.label_13.setText(_translate("MainWindow", "Close"))
        self.label_14.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Wednesday), _translate("MainWindow", "Wednesdy"))
        self.label_15.setText(_translate("MainWindow", "Open"))
        self.label_16.setText(_translate("MainWindow", "Open"))
        self.label_17.setText(_translate("MainWindow", "Close"))
        self.label_18.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Thursday), _translate("MainWindow", "Thursday"))
        self.label_19.setText(_translate("MainWindow", "Open"))
        self.label_20.setText(_translate("MainWindow", "Open"))
        self.label_21.setText(_translate("MainWindow", "Close"))
        self.label_22.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Friday), _translate("MainWindow", "Friday"))
        self.label_23.setText(_translate("MainWindow", "Open"))
        self.label_24.setText(_translate("MainWindow", "Open"))
        self.label_25.setText(_translate("MainWindow", "Close"))
        self.label_26.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Saturday), _translate("MainWindow", "Saturday"))
        self.label_27.setText(_translate("MainWindow", "Open"))
        self.label_28.setText(_translate("MainWindow", "Open"))
        self.label_29.setText(_translate("MainWindow", "Close"))
        self.label_30.setText(_translate("MainWindow", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Sunday), _translate("MainWindow", "Sunday"))
        self.label_31.setText(_translate("MainWindow", "Attention day:"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Store description"))
        self.pushButton_Create_Store.setText(_translate("MainWindow", "Create Store"))
        self.pushButton_Cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_32.setText(_translate("MainWindow", "Address:"))
        self.label_33.setText(_translate("MainWindow", "N°:"))
        self.label_34.setText(_translate("MainWindow", "Name Shop:"))
        self.pushButton.setText(_translate("MainWindow", "Change"))
        self.pushButton_2.setText(_translate("MainWindow", "Change"))
        self.pushButton_3.setText(_translate("MainWindow", "Change"))
        self.pushButton_4.setText(_translate("MainWindow", "Change"))
        self.pushButton_5.setText(_translate("MainWindow", "Change"))
        self.radioButton_restaurant.setText(_translate("MainWindow", "Restaurant"))
        self.radioButton_kitchen.setText(_translate("MainWindow", "Kitchen"))
        self.radioButton_gardening.setText(_translate("MainWindow", "Gardening"))
        self.radioButton_bookstore.setText(_translate("MainWindow", "Bookstore"))
        self.radioButton_toystore.setText(_translate("MainWindow", "Toy Store"))
        self.radioButton_tools.setText(_translate("MainWindow", "Tools"))
        self.radioButton_other.setText(_translate("MainWindow", "Other"))
        self.radioButton_sports.setText(_translate("MainWindow", "Sports"))